# Generated by Django 5.0.1 on 2024-01-11 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Char',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('life', models.IntegerField()),
                ('Attack', models.IntegerField()),
                ('Defense', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100)),
                ('knight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knight', to='Game.char')),
                ('skeleton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skeleton', to='Game.char')),
            ],
        ),
    ]
