# Generated by Django 5.0.1 on 2024-01-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_delete_battle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='char',
            old_name='Attack',
            new_name='attack',
        ),
        migrations.RenameField(
            model_name='char',
            old_name='Defense',
            new_name='defense',
        ),
        migrations.AddField(
            model_name='char',
            name='job',
            field=models.CharField(default='default_value', max_length=50),
        ),
    ]
